name: fancychat
main: com.radthorne.fancychat.FancyChat
version: 1.0
depend: [PlaceholderAPI]
softdepend: [Vault]
commands:
  fancychat:
    description: fancychat
    usage: /<command>
    aliases: [fc]
  channel:
    description: Channel commands
    usage: /<command>
    aliases: [ch]